# .github/workflows/build-and-upload.yml
name: Build and upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and upload (${{ matrix.recipe }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        recipe:
          - sam-2
          - napari-pyav
          - boxmot
      fail-fast: false

    permissions:
      id-token: write  # required for OIDC / Trusted Publishers

    steps:
      - uses: actions/checkout@v4

      - name: Build recipe
        uses: prefix-dev/rattler-build-action@v0.1
        with:
          recipe-path: recipes/${{ matrix.recipe }}/recipe.yaml
          upload-artifact: true

      - name: Upload to Prefix
        uses: prefix-dev/upload-conda-action@v0.1
        with:
          channel: octron